services:
  # Node.js API Service
  api:
    container_name: template_api
    build:
      context: ./pricefinder-api
    ports:
      - "3001:3001"
    volumes:
      - ./pricefinder-api:/app
      - /app/node_modules

  # React Client Service
  client:
    container_name: template_client
    build:
      context: ./pricefinder-client
    ports:
      - "5173:80"
    depends_on:
      - api
    volumes:
      - ./pricefinder-client:/app
      - /app/node_modules
